name: Deploy to FTP

on:
  push:
    branches:
      - release # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install dependencies
      run: cd novelty-seeking&&npm install
    
    - name: Set up Database Environment
      run: |
        echo "DB_HOST=localhost" >> novelty-seeking/.env
        echo "DB_DATABASE=exbragr_novelty_seeking" >> novelty-seeking/.env
        echo "DB_USERNAME=exbragr_novelty_seeking" >> novelty-seeking/.env
        echo "DB_PASSWORD=${{ secrets.FTP_SECRET }}" >> novelty-seeking/.env
    
    - name: Set up React Environment
      run: echo "REACT_APP_VALID_TOKEN=${{ secrets.VALID_TOKEN }}" >> novelty-seeking/.env


    - name: Build React app
      env:
        CI: false
      run: cd novelty-seeking && npm run build

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_SECRET }}
        local-dir: novelty-seeking/build/
        server-dir: /novelty_seeking/ # Change this to the desired remote directory
